### ISSUE TITLE
BEC from Turton sheets returns an error if no data in Miscellaneous items

### ISSUE THREAD

**Issue by SchalkCloete** [SINTEF/Scale-Coupled-Open-Innovation-Network#1]
In the Plant CAPEX file, the BEC (line 6) for the Turton sheets only works when the Turton sheet contains data both in the top section and the Miscellaneous items section below it. Then one has to go and modify the formula manually to exclude the Miscellaneous items cell. Can you find a way to make it work generically.

**Comment by carnaiz88** [comment]
Yes, I just slightly changed the formulas in the sheets so that if there are no elements (either of Turton or Miscellaneous) the cell returns a value of 0, and the BEC is calculated correctly in the CAPEX sheet. Note however that the addition of new sheets will still require manual linking to the CAPEX sheet by the user.
